name: Build React Native Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install
          npx pod-install ios

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # Chỉ định phân phối JDK
          architecture: x64

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          sudo apt install -y android-sdk
          sudo apt install -y gradle

      - name: Build APK
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease

      - name: Check if APK exists
        run: |
          if [ -f android/app/build/outputs/apk/release/app-release.apk ]; then echo "APK exists"; else echo "APK not found"; fi
